### ISSUE TITLE
Which units have the current axes value??

### ISSUE THREAD

**Issue by kacunar** [gpvidal/adxl355-python#1]
I dont know which unit have the output of the reading. It doesnt seem m/s^2 or g.

**Comment by gpvidal** [comment]
Hi!
According to ADXL355 datasheet, the unit is `LSB/g`. You can see this info [here](http://www.analog.com/media/en/technical-documentation/data-sheets/adxl354_355.pdf).

**Comment by kacunar** [comment]
ohh! thank you!! do you know what is the correctly form to convert this unit to g? I dont see it clear in the datasheet. And second, can i use this library with this adxl355 http://www.analog.com/media/en/technical-documentation/user-guides/EVAL-ADXL354-355-UG-1030.pdf ??  i see that there are some differents pins.

**Comment by gpvidal** [comment]
To convert to `g`, you should multiply the output value by the scale factor. An example [here](https://ez.analog.com/thread/84039).

If you have the evaluation board and a SPI interface (like in RPi), you can use this library. If you wire the accelerometer correctly, it should be the same.

**Comment by kacunar** [comment]
But if the output have LSB/g unit and the scale factor have ug/LSB as unit, why the result dont have g as unit?? 

But the evaluation board have pins like v1p8ana and v1p8dig that i dont know how to wire  for a correctly performance.  

Thank you

**Comment by kacunar** [comment]
Hello

i have tried to install SPI python library for 3 days without any good notice.  The commands that you have in the readme to know how to install SPI library didnt work for me.  Do yo have any idea how to resolve this problem?

**Comment by gpvidal** [comment]
Hi!

Are you tried in RPi?

**Comment by kacunar** [comment]
Yeah, i have a RaspberryPi 3 model B.

**Comment by gpvidal** [comment]
> But if the output have LSB/g unit and the scale factor have ug/LSB as unit, why the result dont have g as unit??

Mmm.. I don't know, but if you see the datasheet for that model, the units are the same.

> But the evaluation board have pins like v1p8ana and v1p8dig that i dont know how to wire for a correctly performance.

Can you post an image (or link)?

**Comment by gpvidal** [comment]
> Yeah, i have a RaspberryPi 3 model B.

And Raspbian Stretch Lite as OS?

**Comment by kacunar** [comment]
The image of the eval board pins.
![image](https://user-images.githubusercontent.com/32245492/39320436-b1bcb230-4949-11e8-9dc2-eba227ff7d66.png)
 I have Raspbian GNU/Linux 8 (jessie) as OS

**Comment by gpvidal** [comment]
> I have Raspbian GNU/Linux 8 (jessie) as OS

Do you have `python3` installed?

**Comment by gpvidal** [comment]
> But the evaluation board have pins like v1p8ana and v1p8dig that i dont know how to wire for a correctly performance.

From [here](http://www.analog.com/en/products/sensors-mems/accelerometers/adxl354.html?doc=ADXL354_355.pdf#product-overview):

* Voltage range options
    * VSUPPLY with internal regulators: 2.25 V to 3.6 V
    * V1P8ANA, V1P8DIG with internal low dropout regulator (LDO) bypassed: 1.8 V typical ± 10%

So, those pins are optional
